eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
---
spring:
  kafka:
    properties:
      bootstrap:
        servers: pkc-p11xm.us-east-1.aws.confluent.cloud:9092
      security:
        protocol: SASL_SSL
        sasl:
          mechanism: PLAIN
          jaas:
            config: org.apache.kafka.common.security.plain.PlainLoginModule   required username='ET37EL5BXSTAQNSG'   password='4Lny4Ls9hMydyeVUm9cnSv5bfWWWrm37+AedTscmcb0/vjy77AhXX5mYwZ4yZ1PR'
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  application:
    name: fast-food-app-orders
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb+srv://backend:Madara*123@cluster0.f4o6lo5.mongodb.net/ordersDb?retryWrites=true&w=majority
server:
  port: 8071
---
